name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  buildLinux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 3.4.7

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp
          haxelib install lime 7.7.0
          haxelib install openfl 8.7.0
          haxelib install flixel 5.2.2
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install flixel-addons
          haxelib install tjson
          haxelib install hxjsonast
          haxelib git linc_luajit https://github.com/AndreiRudenko/linc_luajit
          haxelib install hscript
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib install hxcpp-debug-server
          haxelib list

      - name: Create Version Tag
        run: echo "${{ github.run_id }}" > VERSION

      - name: Compile (Linux)
        run: haxelib run lime build Project.xml linux --app-version="0.5.2h-${{ github.run_id }}"

      - name: Publish Artifact (Linux)
        uses: actions/upload-artifact@v4
        with:
          name: linuxBuild
          path: export/release/linux/bin

  buildWindows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 3.4.7

      - name: Install Haxelib
        shell: cmd
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp
          haxelib install lime 7.7.0
          haxelib install openfl 8.7.0
          haxelib install flixel 5.2.2
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install flixel-addons
          haxelib install tjson
          haxelib install hxjsonast
          haxelib git linc_luajit https://github.com/AndreiRudenko/linc_luajit
          haxelib install hscript
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib install hxcpp-debug-server
          haxelib list

      - name: Create Version Tag
        run: echo "${{ github.run_id }}" > VERSION

      - name: Compile (Windows)
        run: haxelib run lime build windows --app-version="0.5.2h-${{ github.run_id }}"

      - name: Publish Artifact (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: windowsBuild
          path: export/release/windows/bin

  buildMac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 3.4.7

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp
          haxelib install lime 7.7.0
          haxelib install openfl 8.7.0
          haxelib install flixel 5.2.2
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install flixel-addons
          haxelib install tjson
          haxelib install hxjsonast
          haxelib git linc_luajit https://github.com/AndreiRudenko/linc_luajit
          haxelib install hscript
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib install hxcpp-debug-server
          haxelib list

      - name: Create Version Tag
        run: echo "${{ github.run_id }}" > VERSION

      - name: Compile (macOS)
        run: haxelib run lime build mac --app-version="0.5.2h-${{ github.run_id }}"

      - name: Publish Artifact (macOS)
        uses: actions/upload-artifact@v4
        with:
          name: macBuild
          path: export/release/macos/bin
